name = "BatchedMetrics"
uuid = "e861f8d1-3c50-4b1d-87ff-21c486aaf2d0"
authors = ["Joshua Billson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
